<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Solicitud_model extends CI_Model
{
    public function __construct()
    {
        parent::__construct();
    }

    /*
     * Get solicitude by id_solicitud
     */
    public function get_solicitude($id_solicitud)
    {
        return $this->db->get_where('solicitudes', array('id_solicitud' => $id_solicitud))->row_array();
    }

    /*
     * Get all solicitudes
     */
    public function get_all_solicitudes()
    {
        $this->db->where('status_solicitud ', 0);
        $this->db->order_by('id_solicitud', 'desc');
        return $this->db->get('solicitudes')->result_array();
    }

    public function get_all_solicitudes_with_filter($carrera,$semestre,$estado)
    {
        $this->db->where('status_solicitud', 0);
        if($carrera == '' && $semestre == '' && $estado == ''){
        }else if($carrera != '' && $semestre == '' && $estado == ''){
            $this->db->where('carrera_id', $carrera);
        }else if($carrera == '' && $semestre != '' && $estado == ''){
            $this->db->where('semestre_id', $semestre);
        }else if($carrera == '' && $semestre == '' && $estado != ''){
            $this->db->where('estado_solicitud', $estado); 
        }else if($carrera != '' && $semestre != '' && $estado != ''){
            $this->db->where('carrera_id', $carrera);
            $this->db->where('semestre_id', $semestre);
            $this->db->where('estado_solicitud', $estado);  
        }else if($carrera != '' && $semestre != '' && $estado == ''){
            $this->db->where('carrera_id', $carrera);
            $this->db->where('semestre_id', $semestre);     
        }else if($carrera == '' && $semestre != '' && $estado != ''){
            $this->db->where('estado_solicitud', $estado);
            $this->db->where('semestre_id', $semestre);
        }else if($carrera != '' && $semestre == '' && $estado != ''){
            $this->db->where('carrera_id', $carrera);
            $this->db->where('estado_solicitud', $estado);
        }

        $this->db->order_by('id_solicitud', 'desc');
        return $this->db->get('solicitudes')->result_array();
    }

    /*
     * Get all solicitudes for alumn
     */
    public function get_all_my_solicitudes($idalumno)
    {
        $this->db->where('status_solicitud ', 0);
        $this->db->where('usuario_id ', $idalumno);
        $this->db->order_by('id_solicitud', 'desc');
        return $this->db->get('solicitudes')->result_array();
    }

    /*
     * Get all solicitudes for alumn inactivas
     */
    public function get_all_my_solicitudes_inactive($idalumno)
    {
        $this->db->where('status_solicitud ', 1);
        $this->db->where('usuario_id ', $idalumno);
        $this->db->order_by('id_solicitud', 'desc');
        return $this->db->get('solicitudes')->result_array();
    }

    public function get_all_solicitudes_inactive()
    {
        $this->db->where('status_solicitud ', 1);
        $this->db->order_by('id_solicitud', 'desc');
        return $this->db->get('solicitudes')->result_array();
    }

    /*
     * function to add new solicitude
     */
    public function add_solicitude($params)
    {
        $this->db->insert('solicitudes', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update solicitude
     */
    public function update_solicitude($id_solicitud, $params)
    {
        $this->db->where('id_solicitud', $id_solicitud);
        return $this->db->update('solicitudes', $params);
    }

    /*
     * function to delete solicitude
     */
    public function delete_solicitude($id_solicitud)
    {
        return $this->db->delete('solicitudes', array('id_solicitud' => $id_solicitud));
    }

    public function updatestatus($id_solicitud, $tipo)
    {
        $solicitud = array(
            'status_solicitud' => $tipo,
        );

        $this->db->where('id_solicitud ', $id_solicitud);
        return $this->db->update('solicitudes', $solicitud);
    }

    public function obtenerFechaSolicitud($id_solicitud, $tipo)
    {
        $this->db->where('id_solicitud', $id_solicitud);

        $query = $this->db->get('solicitudes');

        $ret = $query->row();

        if ($tipo == 1) {
            return $ret->fecha_inicio_soliciud;
        } else if ($tipo == 2) {
            return $ret->fecha_inicio_soliciud;
        } else {
            return $ret->fecha_alta_solicitud;
        }
    }

    public function getMesSolicitud($fecha)
    {
        $inicio_month_number = date_format(date_create($fecha), 'n');
        switch ($inicio_month_number) {
            case 1:
                return "enero";
                break;
            case 2:
                return "febrero";
                break;
            case 3:
                return "marzo";
                break;
            case 4:
                return "abril";
                break;
            case 5:
                return "mayo";
                break;
            case 6:
                return "junio";
                break;
            case 7:
                return "julio";
                break;
            case 8:
                return "agosto";
                break;
            case 9:
                return "septiembre";
                break;
            case 10:
                return "octubre";
                break;
            case 11:
                return "noviembre";
                break;
            case 12:
                return "diciembre";
                break;
        }
    }

    public function traerDocumento($id_solicitud, $tipo_documento)
    {

        $query = "SELECT * FROM `documentos` WHERE solicitud_id = $id_solicitud AND tipo_documento = $tipo_documento";

        $res = $this->db->query($query);

        if ($res->num_rows() > 0) {
            return $res->result("array");
        }else{
            return "NOHAY";
        }
        
    }

    public function actualizarDocumentoDB($id_solicitud,$nombrefinalarchivo,$tipoarchivo)
    {
        $documento = array(
            'nombre_documento' => $nombrefinalarchivo,
        );

        $this->db->where('solicitud_id ', $id_solicitud);
        $this->db->where('tipo_documento', $tipoarchivo);
        return $this->db->update('documentos', $documento);
    }

    public function agregarDocumentoDB($id_solicitud,$nombrefinalarchivo,$tipoarchivo)
    {
        $documento = array(
            'id_documento' => null,
            'nombre_documento' => $nombrefinalarchivo,
            'tipo_documento' => $tipoarchivo,
            'fecha_documento' => date('Y-m-d'),
            'solicitud_id' => $id_solicitud
        );
        $this->db->insert('documentos', $documento);
        return $this->db->insert_id();
    }

    public function contarEstados($tipo)
    {
        $query = "SELECT * FROM `solicitudes` WHERE estado_solicitud = ".$tipo;

        $res = $this->db->query($query);

        return $res->num_rows();
    }

    public function traerInformeTodos()
    {
        $query = "SELECT id_solicitud, 
                        nombres_alumno_solicitud, 
                        apellidos_alumno_solicitud, 
                        matricula_solicitud, 
                        carrera_id, 
                        semestre_id, 
                        nombre_empresa_solicitud,
                        nombre_dirigido_solicitud, 
                        puesto_solicitud, 
                        horario_solicitud, 
                        conocimiento_solicitud, 
                        nombre_proyecto_solicitud, 
                        descripcion_solicitud, 
                        nombre_jefe_solicitud, 
                        cargo_jefe_solicitud, 
                        celular_alumno_solicitud, 
                        correo_alumno_solicitud, 
                        fecha_inicio_soliciud, 
                        fecha_final_solicitud, 
                        fecha_alta_solicitud, 
                        estado_solicitud FROM `solicitudes` WHERE status_solicitud = 0";

        $res = $this->db->query($query);

        return $res->result_array();
    }

    public function traerInformePorCarrera($idcarrera)
    {
        $query = "SELECT id_solicitud, 
                        nombres_alumno_solicitud, 
                        apellidos_alumno_solicitud, 
                        matricula_solicitud, 
                        carrera_id, 
                        semestre_id, 
                        nombre_empresa_solicitud,
                        nombre_dirigido_solicitud, 
                        puesto_solicitud, 
                        horario_solicitud, 
                        conocimiento_solicitud, 
                        nombre_proyecto_solicitud, 
                        descripcion_solicitud, 
                        nombre_jefe_solicitud, 
                        cargo_jefe_solicitud, 
                        celular_alumno_solicitud, 
                        correo_alumno_solicitud, 
                        fecha_inicio_soliciud, 
                        fecha_final_solicitud, 
                        fecha_alta_solicitud, 
                        estado_solicitud FROM `solicitudes` WHERE carrera_id = ".$idcarrera." AND status_solicitud = 0";

        $res = $this->db->query($query);

        return $res->result_array();
    }

    public function traerInformePorSemestre($idsemestre)
    {
        $query = "SELECT id_solicitud, 
                        nombres_alumno_solicitud, 
                        apellidos_alumno_solicitud, 
                        matricula_solicitud, 
                        carrera_id, 
                        semestre_id, 
                        nombre_empresa_solicitud,
                        nombre_dirigido_solicitud, 
                        puesto_solicitud, 
                        horario_solicitud, 
                        conocimiento_solicitud, 
                        nombre_proyecto_solicitud, 
                        descripcion_solicitud, 
                        nombre_jefe_solicitud, 
                        cargo_jefe_solicitud, 
                        celular_alumno_solicitud, 
                        correo_alumno_solicitud, 
                        fecha_inicio_soliciud, 
                        fecha_final_solicitud, 
                        fecha_alta_solicitud, 
                        estado_solicitud FROM `solicitudes` WHERE semestre_id = ".$idsemestre." AND status_solicitud = 0";

        $res = $this->db->query($query);

        return $res->result_array();
    }

    public function traerInformePorEtapa($idetapa)
    {
        $query = "SELECT id_solicitud, 
                        nombres_alumno_solicitud, 
                        apellidos_alumno_solicitud, 
                        matricula_solicitud, 
                        carrera_id, 
                        semestre_id, 
                        nombre_empresa_solicitud,
                        nombre_dirigido_solicitud, 
                        puesto_solicitud, 
                        horario_solicitud, 
                        conocimiento_solicitud, 
                        nombre_proyecto_solicitud, 
                        descripcion_solicitud, 
                        nombre_jefe_solicitud, 
                        cargo_jefe_solicitud, 
                        celular_alumno_solicitud, 
                        correo_alumno_solicitud, 
                        fecha_inicio_soliciud, 
                        fecha_final_solicitud, 
                        fecha_alta_solicitud, 
                        estado_solicitud FROM `solicitudes` WHERE estado_solicitud = ".$idetapa;

        $res = $this->db->query($query);

        return $res->result_array();
    }
}
